# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet C:/project/picoblaze_example/picoblaze_example.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/project/picoblaze_example/picoblaze_example.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/project/picoblaze_example/picoblaze_example.srcs/sources_1/imports/Verilog/kcpsm6.v
  C:/project/picoblaze_example/picoblaze_example.srcs/sources_1/imports/KCPSM6_Release8_31March14/asm_new.v
  C:/project/picoblaze_example/picoblaze_example.srcs/sources_1/imports/Verilog/kcpsm6_design_template.v
  C:/project/picoblaze_example/picoblaze_example.srcs/sources_1/new/kpsm_top.v
}
read_xdc C:/project/picoblaze_example/picoblaze_example.srcs/constrs_1/new/my_constr.xdc
set_property used_in_implementation false [get_files C:/project/picoblaze_example/picoblaze_example.srcs/constrs_1/new/my_constr.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/project/picoblaze_example/picoblaze_example.cache/wt [current_project]
set_property parent.project_dir C:/project/picoblaze_example [current_project]
synth_design -top kpsm_top -part xc7k325tffg900-2
write_checkpoint kpsm_top.dcp
report_utilization -file kpsm_top_utilization_synth.rpt -pb kpsm_top_utilization_synth.pb
